### ISSUE TITLE
cli3 引入报错

### ISSUE THREAD

**Issue by furylee** [buuing/right-menu#40]
```
This dependency was not found:

* vue-demi in ./node_modules/@right-menu/vue/dist/index.esm.js

To install it, you can run: npm install --save vue-demi

遂安装
This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs

To install it, you can run: npm install --save @vue/composition-api/dist/vue-composition-api.mjs


```

**Comment by buuing** [comment]
这都给你提示了, 你就安装一下呗
```
npm i vue-demi @vue/composition-api
```

**Comment by buuing** [comment]
低版本的webpack可能会出现依赖安装失败的情况, 所以你手动安装一下再试试

**Comment by furylee** [comment]
> 



> 低版本的webpack可能会出现依赖安装失败的情况, 所以你手动安装一下再试试

搞过了,不行

**Comment by buuing** [comment]
你是说, 使用这两个命令之后依旧无法使用是嘛

**Comment by buuing** [comment]
我有个方案, 那就是你试试CDN链接, 这个可以避开依赖导致的问题

**Comment by furylee** [comment]
> 我有个方案, 那就是你试试CDN链接, 这个可以避开依赖导致的问题

怎么搞,没这么搞过?主要是就算能解决问题,我也不能这么做啊

**Comment by buuing** [comment]
....为啥, CDN链接很稳定, 可以放心使用

**Comment by furylee** [comment]
> ....为啥, CDN链接很稳定, 可以放心使用

你要不要在cli3上复现下试试,不然这螃蟹我不敢吃啊

**Comment by buuing** [comment]
你找到那个`index.html`在后面单独引入下面的标签即可
```html
<script src="https://cdn.jsdelivr.net/combine/npm/@vue/composition-api@1.2.4,npm/vue-demi@0.11.4/lib/index.iife.min.js,npm/@right-menu/vue@0.0.4"></script>
```

**Comment by buuing** [comment]
> 你要不要在cli3上复现下试试,不然这螃蟹我不敢吃啊

这是依赖冲突问题, 我没有你项目的那些依赖, 所以无法复现问题, `vue-demi`就是很难用, 现在为了兼容vue2和vue3没办法

**Comment by buuing** [comment]
不信的话, 你用vue-cli3创建一个空的项目, 你去安装然后使用, 你会发现, 根本不会报错

**Comment by buuing** [comment]
哦对了, 你要是不想用CDN, 也可以直接参考文档里的在js中使用的方式, 源码包没有任何依赖

**Comment by furylee** [comment]
https://codesandbox.io/s/pensive-burnell-u8wke?file=/src/components/HelloWorld.vue  无论在本地还是codepen上都不行

**Comment by furylee** [comment]
Could not find dependency: 'vue-demi' relative to '/node_modules/@right-menu/vue/dist/index.esm.js'  原因都是这个，安装了也解决不了问题

**Comment by buuing** [comment]
`Could not find dependency: 'vue-demi' relative to '/node_modules/@right-menu/vue/dist/index.esm.js'`
这报错提示不是有吗, 上面都没有`node_modules`咋依赖???

**Comment by furylee** [comment]
问题是本地新建的cli也没法用啊

**Comment by buuing** [comment]
这样的吗, 那你加我个微信`new_ldq`

**Comment by buuing** [comment]
我刚试了一下, 本地cli搭建的vue2.5的项目可以使用, 无报错

**Comment by single-ing** [comment]
我也遇到了这个鬼操作，日志：
PS D:\item\gather-ui> **npm install @right-menu/vue@0.0.4**

added 2 packages in 3s
PS D:\item\gather-ui> **npm install**

up to date in 2s
PS D:\item\gather-ui> **npm run dev**

> gather-ui@1.0.0 dev
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

(node:142240) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 24% building modules 120/139 modules 19 active ...index=0!D:\item\gather-ui\src\App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization                                                                 

 ERROR  Failed to compile with 1 errors                                                                                                                                                                        下午5:01:00
This dependency was not found:


To install it, you can run: npm install --save vue-demi
终止批处理操作吗(Y/N)?
^C
PS D:\item\gather-ui> **npm install --save vue-demi**

added 1 package in 3s
PS D:\item\gather-ui> **npm run dev**

> gather-ui@1.0.0 dev
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

(node:145052) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 23% building modules 116/139 modules 23 active ...index=0!D:\item\gather-ui\src\App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization                                                                 

 ERROR  Failed to compile with 1 errors                                                                                                                                                                        下午5:04:55
This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs

To install it, you can run: npm install --save @vue/composition-api/dist/vue-composition-api.mjs
终止批处理操作吗(Y/N)?
^C
PS D:\item\gather-ui> **npm install --save @vue/composition-api/dist/vue-composition-api.mjs**
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\item\gather-ui\@vue\composition-api\dist\vue-composition-api.mjs/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\item\gather-ui\@vue\composition-api\dist\vue-composition-api.mjs\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\tools\nodejs\node_cache\_logs\2022-03-08T09_05_38_071Z-debug.log

**Comment by buuing** [comment]
安装一下, 你这个不是有提示吗

```
npm install --save @vue/composition-api
```

**Comment by buuing** [comment]
如果还是没能解决, 我今晚把`vue2`和`vue3`分开打包, 不混在一起了

**Comment by single-ing** [comment]
可以了，安装步骤还有点多......

**Comment by buuing** [comment]
没办法, `vue2`和`vue3`之间插件不能通用, 我只能找了个工具才能做到一起打包

代价就是安装的时候, 少部分情况下会出现依赖安装不上的问题, 才需要手动安装一下, 除非我单独给`vue2`和`vue3`打两个包

但是如果这样做, 用户使用的时候引入路径还得区分一下, 所以vue3这个搞得挺麻烦的, 除非vue3可以尽快的兼容一下vue2的插件
