### ISSUE TITLE
事件菜单能携带参数吗

### ISSUE THREAD

**Issue by single-ing** [buuing/right-menu#46]
菜单的参数传递
如
标签上for循环，给事件菜单赋值上对应的参数

**Comment by buuing** [comment]
没懂啥意思, 描述的具体一下

**Comment by single-ing** [comment]
菜单点击事件怎么携带参数

**Comment by buuing** [comment]
> 菜单点击事件怎么携带参数

可以的, 你贴一下代码, 我看看你怎么用的

**Comment by single-ing** [comment]
晚点或明天，文档怎么没看到有介绍这一块的内容

**Comment by buuing** [comment]
> 晚点或明天，文档怎么没看到有介绍这一块的内容

文档比较简洁, 月底我补充一些示例

**Comment by single-ing** [comment]
用法跟文档的一样，只是有跟for循环结合
<el-tag v-for="item in list" :key="item.id" v-menu="options">
</el-tag>
export default {
  data () {
    return {
      options: [{
        type: 'li', // type为li是普通按钮
        text: '复制(C)', // 按钮的名称
        callback: () => alert('点击了复制') // 回调函数
      }]
    }
  }
}
</script>

**Comment by single-ing** [comment]
<el-tag v-for="item in list" :key="item.id" v-menu="options">

**Comment by single-ing** [comment]
标签被和谐了
用法：
v-for="item in list" :key="item.id" v-menu="options"

**Comment by buuing** [comment]
```vue
<template>
  <div>
    <p v-for="item in 6" :key="item" v-menu="getOptions(item)">{{item}}</p>
  </div>
</template>

<script>
export default {
  methods: {
    getOptions(item) {
      return [
        {
          type: 'li',
          text: item,
          callback() {
            console.log(item)
          }
        }
      ]
    }
  }
}
</script>
```

你先这样用吧, 我也忘了应该如何传参了, 改天我把文档补充一下

**Comment by buuing** [comment]
用着顺手可以点个star支持一下

**Comment by single-ing** [comment]
star已支持哦，明天我研究研究

**Comment by single-ing** [comment]
建议把这个用法加入到文档
<template>
  <div>
    <p v-for="item in 6" :key="item" v-menu="getOptions(item)">{{item}}</p>
  </div>
</template>

<script>
export default {
  methods: {
    getOptions(item) {
      return [
        {
          type: 'li',
          text: item,
          callback() {
            console.log(item)
          }
        }
      ]
    }
  }
}
</script>

，,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
文档介绍的用法是这样的
<script>
export default {
  data () {
    return {
      options: [{
        type: 'li', // type为li是普通按钮
        text: '复制(C)', // 按钮的名称
        callback: () => alert('点击了复制') // 回调函数
      }]
    }
  }
}
</script>

**Comment by single-ing** [comment]
这个传参用法可以使用，
文档没有介绍这样的写法，而是下面这样的
export default {
  data () {
    return {
      options: [{
        type: 'li', // type为li是普通按钮
        text: '复制(C)', // 按钮的名称
        callback: () => alert('点击了复制') // 回调函数
      }]
    }
  }
}
