### ISSUE TITLE
指令组件下maxWidth， minWidth无效

### ISSUE THREAD

**Issue by single-ing** [buuing/right-menu#47]
`

<el-tag v-for="(item,index) in $store.state.tagRouters" :key="index" closable v-menu="rightMenu(item)"
    maxWidth="100px" minWidth="100px" style="cursor: pointer;margin-right: 3px">
    {{item.name}}
</el-tag>

<right-menu maxWidth="100px" minWidth="100px" :options="rightMenu('1')">
    <el-tag v-for="(item,index) in $store.state.tagRouters" :key="index" closable
        style="cursor: pointer;margin-right: 3px">
        {{item.name}}
    </el-tag>
</right-menu>
`

**Comment by single-ing** [comment]
`

<el-tag v-for="(item,index) in $store.state.tagRouters" :key="index" closable
    size="small" @close="tagClose(item)" @click="tagClick(item.path)"
    :type="item.path === $route.path?'dark':'info'" v-menu="rightMenu(item)"
    maxWidth="100px" minWidth="100px" style="cursor: pointer;margin-right: 3px">
    {{item.name}}
</el-tag>

<right-menu maxWidth="100px" minWidth="100px" :options="rightMenu('1')">
    <el-tag v-for="(item,index) in $store.state.tagRouters" :key="index" closable
        size="small" @close="tagClose(item)" @click="tagClick(item.path)"
        :type="item.path === $route.path?'dark':'info'"
        style="cursor: pointer;margin-right: 3px">
        {{item.name}}
    </el-tag>
</right-menu>`

**Comment by single-ing** [comment]
`

<div v-for="(item,index) in $store.state.tagRouters" :key="index" closable
    size="small" @close="tagClose(item)" @click="tagClick(item.path)"
    :type="item.path === $route.path?'dark':'info'" v-menu="rightMenu(item)"
    maxWidth="100px" minWidth="100px" style="cursor: pointer;margin-right: 3px">
    {{item.name}}
</div>

<right-menu maxWidth="100px" minWidth="100px" :options="rightMenu('1')">
    <div v-for="(item,index) in $store.state.tagRouters" :key="index" closable
        size="small" @close="tagClose(item)" @click="tagClick(item.path)"
        :type="item.path === $route.path?'dark':'info'"
        style="cursor: pointer;margin-right: 3px">
        {{item.name}}
    </div>
</right-menu>
`

**Comment by buuing** [comment]
我不知道你对vue的指令组件是否有什么误解........

你把 maxWidth， minWidth 加在普通dom上, 我确实拿不到

实际上, `v-menu`就是一个简写方式, 如果你想使用 `right-menu` 的全部功能, 那你只能改成`<right-menu />`这种方式
